"""Add sub_type to FitnessActivity table

Revision ID: c684cb3c3ec2
Revises: d76f327404a3
Create Date: 2025-08-27 16:41:21.004538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c684cb3c3ec2'
down_revision = 'd76f327404a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('total_workout_volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_reward_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('total_reward_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_workout_volume',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fitness_activity', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('sub_type')

    # ### end Alembic commands ###
