"""Add total_workout_volume and total_reward_score to User model

Revision ID: d76f327404a3
Revises: 
Create Date: 2025-08-27 16:20:42.046484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd76f327404a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('profile_pic', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.Column('height', mysql.FLOAT(), nullable=True),
    sa.Column('goal', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bmi', mysql.FLOAT(), nullable=True),
    sa.Column('bmr', mysql.FLOAT(), nullable=True),
    sa.Column('maintenance_calories', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
